### ISSUE TITLE
documentation- Adapter Template Improvements

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/documentation#10]
The Adapter Template currently creates an extra folder that does not comply with the BHoM, and leads to an requirement to move files and folder around after it has been used. See [TheAdapter Wiki](https://github.com/BHoM/documentation/wiki/BH.Adapter-%E2%80%90-Linking-to-Commercial-Software#a-creating-a-new-software-toolkit-with-the-template)

Could make use of the template wizard to further improve and customise the templates:
https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-wizards-with-project-templates?view=vs-2017

**Comment by alelom** [comment]
Closed, see https://github.com/BHoM/documentation/issues/18
