### ISSUE TITLE
Assigning ETABS Pier label by BHoM

### ISSUE THREAD

**Issue by samloo1997** [BHoM/documentation#106]
Hi,
i saw there is a "Pier Label" in the BHoM object,
i wonder if there is any way to assign the pier label to the object through rhino grasshopper as i really cant find anything thing that can connect to
![image](https://github.com/BHoM/documentation/assets/139096240/505544ca-4998-4840-b68d-a185fa58c2ca)

**Comment by FraserGreenroyd** [comment]
@peterjamesnugent @IsakNaslundBh do either of you know?

**Comment by peterjamesnugent** [comment]
Hi @samloo1997, the `Pier` object you are referring to is a `Fragment`. `Pier`s, along with `Spandrel`s and `Diaphragm`s can be attached to a `Panel` by assigning a `Fragment`. You can add a `Fragment` using the following method:
https://github.com/BHoM/BHoM_Engine/blob/develop/BHoM_Engine/Modify/AddFragment.cs

When you push a `Panel` object in to ETABS, it will also asign the label to your `Pier` as shown here:
https://github.com/BHoM/ETABS_Toolkit/blob/5c76b9b9173f0dcd0b255809d2e1f52e85e64efb/Etabs_Adapter/CRUD/Create/Panel.cs#L164-L168

Similarly, when you `Pull` back from ETABS, it will look for a `Pier` and assign it to your `Panel`:
https://github.com/BHoM/ETABS_Toolkit/blob/5c76b9b9173f0dcd0b255809d2e1f52e85e64efb/Etabs_Adapter/CRUD/Read/Panel.cs#L115-L118

Happy to answer any further questions if you have them.

**Comment by samloo1997** [comment]
thank you so much! it works perfectly.
![image](https://github.com/BHoM/documentation/assets/139096240/85df55cc-7945-490b-bfe5-be2e5029129e)
attached here the grasshopper code for those have similar problems
