### ISSUE TITLE
documentation - Engine Template Improvements

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/documentation#11]
The engine templates currently adds an extra unwanted namespace layer to the objects being created:

![image](https://user-images.githubusercontent.com/22005920/53183659-0006ff00-35fc-11e9-8479-1af17eb7aac0.png)

Could be improved further by making use of:

https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-wizards-with-project-templates?view=vs-2017

**Comment by FraserGreenroyd** [comment]
I believe this has been solved by the updated template repository so closing for now but feel free to reopen if there is an issue still that I've missed @IsakNaslundBh

**Comment by IsakNaslundBh** [comment]
Not closed out @FraserGreenroyd - this was regarding using the mroe involved way of making item templates making use of VSIX. But do not think the benefit vs time investment of doing this will be worth it hence happy for this to be closed.
