### ISSUE TITLE
Wiki : Documentation of Deprecated Attribute

### ISSUE THREAD

**Issue by al-fisher** [BHoM/documentation#12]

**Comment by al-fisher** [comment]
FYI - uncovered this page https://github.com/BHoM/documentation/wiki/Code-Attributes#deprecated 
Needs to be more discoverable

**Comment by FraserGreenroyd** [comment]
Assigned @alelom during BHoM call to close this out.

**Comment by alelom** [comment]
As discussed with @al-fisher 
added the code attributes page to the right-hand side navigator for now
![image](https://user-images.githubusercontent.com/6352844/60974504-16e78d00-a322-11e9-8a20-8a98fce1c941.png)
will then review the overall organisation and write down new wiki after the BHoM_Adapter refactor exercise is complete
