### ISSUE TITLE
Wiki: Documentation link broken - leads to new page creation

### ISSUE THREAD

**Issue by m-clare** [BHoM/documentation#22]
Under the [Contribute](https://github.com/BHoM/documentation/wiki#contribute) heading, the [BH.Adapter - Linking to Commercial Software link](https://github.com/BHoM/documentation/wiki/BH.Adapter-%E2%80%90-Linking-to-Commercial-Software) redirects to a wiki page creation, rather than content.

**Comment by IsakNaslundBh** [comment]
Was fixed by https://github.com/BHoM/documentation/wiki/Home/_compare/2181e887d0bc1d476fa5d92d24dd167e64468ee5
