### ISSUE TITLE
Create separate page for naming conventions for Issues, Branches, and PRs

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/documentation#34]
Currently this information is scattered about and not linked. PR naming is addressed in Changelog, and Branch naming is addressed in Resolving an Issue. Issue naming is not addressed.

**Comment by al-fisher** [comment]
This is a good idea! @JosefTaylor - always like your comments on clarifying some of our _unintentionally_ opaque conventions 😄 
I would say, also feel free to jump in and create new page/make edits - and share for review with others. Keen it works for widest group possible 😄

**Comment by FraserGreenroyd** [comment]
Documentation has been improved/updated in recent months so considering this issue complete - feel free to reopen if there's anything missing (or open new issues 😄 )
