### ISSUE TITLE
Installer Download

### ISSUE THREAD

**Issue by BenNewman14** [BHoM/documentation#37]
There appears to be an issue with downloading the installer, following the link on https://bhom.xyz/ brings you to the GitHub wiki, but the link there sends you back to https://bhom.xyz/.

The installer in <>code is an older version?

**Comment by FraserGreenroyd** [comment]
Hi @BenNewman14 I've just done a quick test, and clicking the link for downloading the latest 3.3 beta provides me with a pop-up asking where I'd like to save the MSI file, and then loads the wiki in the background. Can I check, do you have your settings set to accept pop-ups and downloads on your browser? It may also be worth clearing the cache before clicking the link

**Comment by BenNewman14** [comment]
Hi Fraser, it looks like it is a pop up blocking issue, as I have been able to download on another machine. Thanks for your help.

**Comment by FraserGreenroyd** [comment]
No worries, glad to be able to help :smile:
