### ISSUE TITLE
Review versioning wiki following recent updates

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/documentation#39]
https://github.com/BHoM/documentation/wiki/Versioning---How-to-modify-code-without-breaking-user-scripts

Some updates have come into the versioning process, @adecler are you happy to do a review in the next few weeks as we go up to beta to make sure the guidance is still accurate following those changes?

May be worth noting/including that only toolkits within beta installers need to do full versioning (though it is available to those in any toolkit of course) but requirements are only on beta installers.

**Comment by adecler** [comment]
Done,

I have 
- updated the section on `How does it work ?` to switch from backward to forward versioning
- added a section on providing messages for items without upgrades or deleted

**Comment by FraserGreenroyd** [comment]
That's great, thanks @adecler 😄
