### ISSUE TITLE
BHoM isntallation keeps failing. 

### ISSUE THREAD

**Issue by shivajreddy** [BHoM/documentation#43]
Using Revit 2022, Dynamo-Revit(in built)2.10 -> once i install BHoM, it shows up on Revit toolbar, and shows up in Excel. But dynamo wouldn't open. I tried reinstalling Revit2022, removed every extra addin, reinstalled BHoM almost a 100 times, but still no luck.

**Comment by pawelbaran** [comment]
Hi @shivajreddy - sorry I missed the issue. Happy to reply though: the problem has been fixed in https://github.com/BHoM/Revit_Toolkit/pull/1137, so you should be good with the build from ca. 10 December 2021 👍

I will close this issue as resolved, but please feel free to reopen if it reoccurs.
