### ISSUE TITLE
Update wiki for IElementM methods

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/documentation#51]
as soon as https://github.com/BHoM/BHoM_Engine/pull/2897 is merged, the table on the wiki [here](https://github.com/BHoM/documentation/wiki/IElement-required-extension-methods) should be update to:

2. It needs to have the following methods implemented in it's oM-specific Engine:

    |Interface | Required methods | Optional methods | When |
    |:-----------|:----------|:----------|:----------|
    | `IElement0D` | <ul><li>`Geometry()`</li> <li>`SetGeometry(Point point)`</li><li>`HasMergeablePropertiesWith(IElement0D)`</li></ul> | <br> |
    | `IElement1D` | <ul><li>`Geometry()`</li> <li>`SetGeometry(ICurve curve)`</li><li>`HasMergeablePropertiesWith(IElement1D)`</li></ul> | <ul><li>`Elements0D()`</li> <li>`SetElements0D(`<br>`List<IElement0D> newElements0D)`</li> <li>`NewElement0D(Point point)`</li></ul> | `IElement1D` which endpoints are defined by `IElement0D` |
    | `IElement2D` | <ul><li>`OutlineElements1D()`</li> <li>`SetOutlineElements1D(`<br>`List<IElement1D> outlineElements1D)`</li> <li>`NewElement1D(ICurve curve)`</li> <li>`HasMergeablePropertiesWith(IElement2D)`</li>  </ul> |<ul><li>`InternalElements2D()`</li>  <li>`NewInternalElement2D()`</li> <li>`SetInternalElements2D(`<br>`List<IElement2D> internalElements2D)`</li></ul> | If the `IElement2D` has internal elements |
    | |
    | `IElementM` | <ul><li>`MaterialComposition()`</li> <li>`SolidVolume()`</li></ul>  <b>or </b> <ul><li>`VolumetricMaterialTakeoff()`</li></ul>
    | | |

**Comment by Lewis-Waugh** [comment]
Wiki updated with text + table above.
