### ISSUE TITLE
Where to get the latest 6.3.beta?

### ISSUE THREAD

**Issue by netsonicyxf** [BHoM/documentation#80]
It still shows 6.2.beta on https://bhom.xyz/

**Comment by FraserGreenroyd** [comment]
Hi @netsonicyxf , the 6.3 milestone concluded on Friday 22nd September with the beta being produced and tested amongst the community - it will be uploaded to the [BHoM.xyz](https://bhom.xyz) website tomorrow (Monday 25th September) once I have managed to close out the milestone fully and set everything up for the 7.0 milestone 😄

**Comment by FraserGreenroyd** [comment]
The [BHoM.xyz](https://bhom.xyz) website has been updated now @netsonicyxf and the 6.3 beta is available to download from there. You may need to clear your cache to see the update (ctrl + f5 should do the trick) 😄
