### ISSUE TITLE
Add index.md page for DevOps 

### ISSUE THREAD

**Issue by al-fisher** [BHoM/documentation#91]
As flagged here: https://github.com/BHoM/documentation/pull/83#issuecomment-1825809465

Add `index.md` page so https://bhom.xyz/documentation/DevOps/ doesn't point to a 404

**Comment by FraserGreenroyd** [comment]
@al-fisher I notice this doesn't have anyone assigned, do you want me to pick this up and get an index page added or are you handling it as part of #92 ? 😄

**Comment by al-fisher** [comment]
Thanks @FraserGreenroyd - happy for you to do once #92 is closed out. Cheers
